// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Label struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LabelSet struct {
	Labels               []*Label `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelSet) Reset()         { *m = LabelSet{} }
func (m *LabelSet) String() string { return proto.CompactTextString(m) }
func (*LabelSet) ProtoMessage()    {}
func (*LabelSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *LabelSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelSet.Unmarshal(m, b)
}
func (m *LabelSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelSet.Marshal(b, m, deterministic)
}
func (m *LabelSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelSet.Merge(m, src)
}
func (m *LabelSet) XXX_Size() int {
	return xxx_messageInfo_LabelSet.Size(m)
}
func (m *LabelSet) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelSet.DiscardUnknown(m)
}

var xxx_messageInfo_LabelSet proto.InternalMessageInfo

func (m *LabelSet) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

type RegisterGuestAccountRequest struct {
	// server ID is the unique ULID of the Waypoint server requesting a
	// guest account. If this server already has a guest account registered,
	// the same token will be returned.
	ServerId             string   `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterGuestAccountRequest) Reset()         { *m = RegisterGuestAccountRequest{} }
func (m *RegisterGuestAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterGuestAccountRequest) ProtoMessage()    {}
func (*RegisterGuestAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *RegisterGuestAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterGuestAccountRequest.Unmarshal(m, b)
}
func (m *RegisterGuestAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterGuestAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterGuestAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterGuestAccountRequest.Merge(m, src)
}
func (m *RegisterGuestAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterGuestAccountRequest.Size(m)
}
func (m *RegisterGuestAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterGuestAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterGuestAccountRequest proto.InternalMessageInfo

func (m *RegisterGuestAccountRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type RegisterGuestAccountResponse struct {
	// API token to use for protected endpoints.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterGuestAccountResponse) Reset()         { *m = RegisterGuestAccountResponse{} }
func (m *RegisterGuestAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterGuestAccountResponse) ProtoMessage()    {}
func (*RegisterGuestAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *RegisterGuestAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterGuestAccountResponse.Unmarshal(m, b)
}
func (m *RegisterGuestAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterGuestAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterGuestAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterGuestAccountResponse.Merge(m, src)
}
func (m *RegisterGuestAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterGuestAccountResponse.Size(m)
}
func (m *RegisterGuestAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterGuestAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterGuestAccountResponse proto.InternalMessageInfo

func (m *RegisterGuestAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterHostnameRequest struct {
	// hostname to register
	//
	// Types that are valid to be assigned to Hostname:
	//	*RegisterHostnameRequest_Generate
	//	*RegisterHostnameRequest_Exact
	Hostname isRegisterHostnameRequest_Hostname `protobuf_oneof:"hostname"`
	// labels to link this hostname to.
	Labels               *LabelSet `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterHostnameRequest) Reset()         { *m = RegisterHostnameRequest{} }
func (m *RegisterHostnameRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterHostnameRequest) ProtoMessage()    {}
func (*RegisterHostnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *RegisterHostnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterHostnameRequest.Unmarshal(m, b)
}
func (m *RegisterHostnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterHostnameRequest.Marshal(b, m, deterministic)
}
func (m *RegisterHostnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterHostnameRequest.Merge(m, src)
}
func (m *RegisterHostnameRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterHostnameRequest.Size(m)
}
func (m *RegisterHostnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterHostnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterHostnameRequest proto.InternalMessageInfo

type isRegisterHostnameRequest_Hostname interface {
	isRegisterHostnameRequest_Hostname()
}

type RegisterHostnameRequest_Generate struct {
	Generate *empty.Empty `protobuf:"bytes,1,opt,name=generate,proto3,oneof"`
}

type RegisterHostnameRequest_Exact struct {
	Exact string `protobuf:"bytes,2,opt,name=exact,proto3,oneof"`
}

func (*RegisterHostnameRequest_Generate) isRegisterHostnameRequest_Hostname() {}

func (*RegisterHostnameRequest_Exact) isRegisterHostnameRequest_Hostname() {}

func (m *RegisterHostnameRequest) GetHostname() isRegisterHostnameRequest_Hostname {
	if m != nil {
		return m.Hostname
	}
	return nil
}

func (m *RegisterHostnameRequest) GetGenerate() *empty.Empty {
	if x, ok := m.GetHostname().(*RegisterHostnameRequest_Generate); ok {
		return x.Generate
	}
	return nil
}

func (m *RegisterHostnameRequest) GetExact() string {
	if x, ok := m.GetHostname().(*RegisterHostnameRequest_Exact); ok {
		return x.Exact
	}
	return ""
}

func (m *RegisterHostnameRequest) GetLabels() *LabelSet {
	if m != nil {
		return m.Labels
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RegisterHostnameRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RegisterHostnameRequest_Generate)(nil),
		(*RegisterHostnameRequest_Exact)(nil),
	}
}

type RegisterHostnameResponse struct {
	Fqdn                 string   `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterHostnameResponse) Reset()         { *m = RegisterHostnameResponse{} }
func (m *RegisterHostnameResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterHostnameResponse) ProtoMessage()    {}
func (*RegisterHostnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *RegisterHostnameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterHostnameResponse.Unmarshal(m, b)
}
func (m *RegisterHostnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterHostnameResponse.Marshal(b, m, deterministic)
}
func (m *RegisterHostnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterHostnameResponse.Merge(m, src)
}
func (m *RegisterHostnameResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterHostnameResponse.Size(m)
}
func (m *RegisterHostnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterHostnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterHostnameResponse proto.InternalMessageInfo

func (m *RegisterHostnameResponse) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

type ListHostnamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostnamesRequest) Reset()         { *m = ListHostnamesRequest{} }
func (m *ListHostnamesRequest) String() string { return proto.CompactTextString(m) }
func (*ListHostnamesRequest) ProtoMessage()    {}
func (*ListHostnamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *ListHostnamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostnamesRequest.Unmarshal(m, b)
}
func (m *ListHostnamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostnamesRequest.Marshal(b, m, deterministic)
}
func (m *ListHostnamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostnamesRequest.Merge(m, src)
}
func (m *ListHostnamesRequest) XXX_Size() int {
	return xxx_messageInfo_ListHostnamesRequest.Size(m)
}
func (m *ListHostnamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostnamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostnamesRequest proto.InternalMessageInfo

type ListHostnamesResponse struct {
	Hostnames            []*ListHostnamesResponse_Hostname `protobuf:"bytes,1,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListHostnamesResponse) Reset()         { *m = ListHostnamesResponse{} }
func (m *ListHostnamesResponse) String() string { return proto.CompactTextString(m) }
func (*ListHostnamesResponse) ProtoMessage()    {}
func (*ListHostnamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *ListHostnamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostnamesResponse.Unmarshal(m, b)
}
func (m *ListHostnamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostnamesResponse.Marshal(b, m, deterministic)
}
func (m *ListHostnamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostnamesResponse.Merge(m, src)
}
func (m *ListHostnamesResponse) XXX_Size() int {
	return xxx_messageInfo_ListHostnamesResponse.Size(m)
}
func (m *ListHostnamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostnamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostnamesResponse proto.InternalMessageInfo

func (m *ListHostnamesResponse) GetHostnames() []*ListHostnamesResponse_Hostname {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

type ListHostnamesResponse_Hostname struct {
	Hostname             string    `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels               *LabelSet `protobuf:"bytes,2,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListHostnamesResponse_Hostname) Reset()         { *m = ListHostnamesResponse_Hostname{} }
func (m *ListHostnamesResponse_Hostname) String() string { return proto.CompactTextString(m) }
func (*ListHostnamesResponse_Hostname) ProtoMessage()    {}
func (*ListHostnamesResponse_Hostname) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7, 0}
}

func (m *ListHostnamesResponse_Hostname) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostnamesResponse_Hostname.Unmarshal(m, b)
}
func (m *ListHostnamesResponse_Hostname) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostnamesResponse_Hostname.Marshal(b, m, deterministic)
}
func (m *ListHostnamesResponse_Hostname) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostnamesResponse_Hostname.Merge(m, src)
}
func (m *ListHostnamesResponse_Hostname) XXX_Size() int {
	return xxx_messageInfo_ListHostnamesResponse_Hostname.Size(m)
}
func (m *ListHostnamesResponse_Hostname) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostnamesResponse_Hostname.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostnamesResponse_Hostname proto.InternalMessageInfo

func (m *ListHostnamesResponse_Hostname) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ListHostnamesResponse_Hostname) GetLabels() *LabelSet {
	if m != nil {
		return m.Labels
	}
	return nil
}

type DeleteHostnameRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHostnameRequest) Reset()         { *m = DeleteHostnameRequest{} }
func (m *DeleteHostnameRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHostnameRequest) ProtoMessage()    {}
func (*DeleteHostnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *DeleteHostnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHostnameRequest.Unmarshal(m, b)
}
func (m *DeleteHostnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHostnameRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHostnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHostnameRequest.Merge(m, src)
}
func (m *DeleteHostnameRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHostnameRequest.Size(m)
}
func (m *DeleteHostnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHostnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHostnameRequest proto.InternalMessageInfo

func (m *DeleteHostnameRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*Label)(nil), "hashicorp.waypoint_hzn.Label")
	proto.RegisterType((*LabelSet)(nil), "hashicorp.waypoint_hzn.LabelSet")
	proto.RegisterType((*RegisterGuestAccountRequest)(nil), "hashicorp.waypoint_hzn.RegisterGuestAccountRequest")
	proto.RegisterType((*RegisterGuestAccountResponse)(nil), "hashicorp.waypoint_hzn.RegisterGuestAccountResponse")
	proto.RegisterType((*RegisterHostnameRequest)(nil), "hashicorp.waypoint_hzn.RegisterHostnameRequest")
	proto.RegisterType((*RegisterHostnameResponse)(nil), "hashicorp.waypoint_hzn.RegisterHostnameResponse")
	proto.RegisterType((*ListHostnamesRequest)(nil), "hashicorp.waypoint_hzn.ListHostnamesRequest")
	proto.RegisterType((*ListHostnamesResponse)(nil), "hashicorp.waypoint_hzn.ListHostnamesResponse")
	proto.RegisterType((*ListHostnamesResponse_Hostname)(nil), "hashicorp.waypoint_hzn.ListHostnamesResponse.Hostname")
	proto.RegisterType((*DeleteHostnameRequest)(nil), "hashicorp.waypoint_hzn.DeleteHostnameRequest")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6f, 0xd2, 0x50,
	0x14, 0xc7, 0x57, 0x0a, 0xb3, 0x3b, 0xf8, 0x83, 0x5c, 0x19, 0x92, 0xa2, 0x09, 0xe9, 0xd3, 0xa2,
	0xae, 0x28, 0x10, 0xe3, 0x8f, 0x44, 0x63, 0xa3, 0x11, 0xe3, 0x9e, 0x3a, 0xe3, 0x92, 0x8a, 0x99,
	0x85, 0x1e, 0x68, 0x63, 0xe9, 0xed, 0xda, 0x0b, 0x38, 0xde, 0x7c, 0xf5, 0xd1, 0x7f, 0x6c, 0xff,
	0x8e, 0x59, 0x7c, 0x30, 0xf4, 0xf6, 0x76, 0x19, 0x02, 0xb2, 0xb7, 0x7b, 0x4f, 0xef, 0xf7, 0xfc,
	0xf8, 0x9c, 0x6f, 0xe1, 0x7a, 0x8c, 0xd1, 0x04, 0x23, 0x3d, 0x8c, 0x28, 0xa3, 0xa4, 0xe2, 0xda,
	0xb1, 0xeb, 0xf5, 0x69, 0x14, 0xea, 0x53, 0xfb, 0x34, 0xa4, 0x5e, 0xc0, 0x8e, 0xdd, 0x59, 0xa0,
	0xd6, 0x86, 0x94, 0x0e, 0x7d, 0x6c, 0x24, 0xaf, 0x7a, 0xe3, 0x41, 0x03, 0x47, 0x21, 0x3b, 0xe5,
	0x22, 0xf5, 0xb6, 0x83, 0x83, 0xb8, 0x31, 0xb1, 0x7d, 0xcf, 0xb1, 0x19, 0xf2, 0xa0, 0xf6, 0x18,
	0x0a, 0x07, 0x76, 0x0f, 0x7d, 0x42, 0x20, 0x1f, 0xd8, 0x23, 0xac, 0x4a, 0x75, 0x69, 0x6f, 0xc7,
	0x4c, 0xce, 0xa4, 0x0c, 0x85, 0x89, 0xed, 0x8f, 0xb1, 0x9a, 0x4b, 0x82, 0xfc, 0xa2, 0x7d, 0x00,
	0x25, 0x91, 0x1c, 0x22, 0x23, 0xaf, 0x60, 0xdb, 0x9f, 0x9f, 0xe3, 0xaa, 0x54, 0x97, 0xf7, 0x8a,
	0xcd, 0x7b, 0xfa, 0xf2, 0xce, 0xf4, 0x44, 0x61, 0x28, 0xe7, 0x46, 0xe1, 0x97, 0x94, 0x53, 0x24,
	0x33, 0x95, 0x69, 0xcf, 0xa1, 0x66, 0xe2, 0xd0, 0x8b, 0x19, 0x46, 0xef, 0xc6, 0x18, 0xb3, 0xd7,
	0xfd, 0x3e, 0x1d, 0x07, 0xcc, 0xc4, 0x93, 0xf9, 0x8d, 0xd4, 0x60, 0x87, 0x0f, 0x7e, 0xec, 0x39,
	0x69, 0x6b, 0x0a, 0x0f, 0xbc, 0x77, 0xb4, 0x36, 0xdc, 0x5d, 0xae, 0x8d, 0x43, 0x1a, 0xc4, 0x49,
	0xfb, 0x8c, 0x7e, 0xc3, 0x20, 0x15, 0xf2, 0x8b, 0xf6, 0x47, 0x82, 0x3b, 0x42, 0xd6, 0xa1, 0x31,
	0x9b, 0x4f, 0x2a, 0xca, 0xb5, 0x41, 0x19, 0x62, 0x80, 0x91, 0xcd, 0x38, 0x88, 0x62, 0xb3, 0xa2,
	0x73, 0xa4, 0xba, 0x40, 0xaa, 0xbf, 0x9d, 0x23, 0xed, 0x6c, 0x99, 0xd9, 0x4b, 0xf2, 0x09, 0x0a,
	0xf8, 0xdd, 0xee, 0x33, 0x8e, 0xc9, 0x78, 0x79, 0x6e, 0xbc, 0x88, 0x9e, 0x95, 0xe4, 0x66, 0xb1,
	0x3b, 0x7d, 0xf0, 0xb9, 0x3b, 0xed, 0x3a, 0xfb, 0x5f, 0xee, 0x5b, 0x05, 0xdb, 0x19, 0x79, 0x81,
	0x25, 0xdb, 0xa1, 0x67, 0xe5, 0x7b, 0x3e, 0x1d, 0x5a, 0xb2, 0x3b, 0x0b, 0xac, 0x6b, 0x2e, 0x8d,
	0xbc, 0x19, 0x0d, 0x2c, 0x45, 0xe0, 0xea, 0x6c, 0x99, 0x3c, 0x1d, 0x31, 0x32, 0xb8, 0x72, 0xd2,
	0x4b, 0x7d, 0x2d, 0xdc, 0x43, 0x64, 0x09, 0xdf, 0x9f, 0x52, 0xae, 0x94, 0xf1, 0x35, 0x6e, 0x81,
	0xe2, 0xa6, 0x43, 0x12, 0xf9, 0xb7, 0x21, 0x69, 0x3a, 0x54, 0xff, 0x9d, 0x3e, 0x05, 0x46, 0x20,
	0x3f, 0x38, 0x71, 0x04, 0xaf, 0xe4, 0xac, 0x55, 0xa0, 0x7c, 0xe0, 0xc5, 0x4c, 0xbc, 0x8d, 0x53,
	0x54, 0xda, 0x99, 0x04, 0xbb, 0x0b, 0x1f, 0xd2, 0x2c, 0x1f, 0x61, 0x47, 0x94, 0x14, 0xb6, 0x78,
	0xb2, 0xb2, 0xf3, 0x65, 0x19, 0xf4, 0xac, 0xb1, 0x8b, 0x44, 0xea, 0x57, 0x50, 0x44, 0x98, 0xa8,
	0x17, 0x43, 0x09, 0x53, 0x64, 0x43, 0x3e, 0xcd, 0xa0, 0xe5, 0x36, 0x83, 0x96, 0x59, 0xb1, 0x05,
	0xbb, 0x6f, 0xd0, 0x47, 0x86, 0x8b, 0xae, 0x58, 0x53, 0xae, 0x79, 0x26, 0x43, 0xf1, 0x48, 0x6c,
	0x6e, 0x16, 0x90, 0x1f, 0x12, 0x94, 0x97, 0x99, 0x92, 0xb4, 0x56, 0xf5, 0xb1, 0xc6, 0xfe, 0x6a,
	0xfb, 0x6a, 0xa2, 0x74, 0x01, 0x63, 0x28, 0x2d, 0xae, 0x98, 0x34, 0xfe, 0x97, 0x69, 0x61, 0x68,
	0xf5, 0xd1, 0xe6, 0x82, 0xb4, 0xac, 0x0f, 0x37, 0x2e, 0xad, 0x93, 0x3c, 0xdc, 0x70, 0xeb, 0xbc,
	0xe0, 0xfe, 0x95, 0x3c, 0x42, 0x8e, 0xe0, 0xe6, 0xe5, 0x6d, 0x91, 0x95, 0x09, 0x96, 0x6e, 0x55,
	0x5d, 0xf1, 0x67, 0x1b, 0x79, 0x2b, 0x17, 0xf6, 0x7a, 0xdb, 0x49, 0xb4, 0xf5, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0xac, 0x98, 0x3b, 0x78, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WaypointHznClient is the client API for WaypointHzn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaypointHznClient interface {
	RegisterGuestAccount(ctx context.Context, in *RegisterGuestAccountRequest, opts ...grpc.CallOption) (*RegisterGuestAccountResponse, error)
	RegisterHostname(ctx context.Context, in *RegisterHostnameRequest, opts ...grpc.CallOption) (*RegisterHostnameResponse, error)
	ListHostnames(ctx context.Context, in *ListHostnamesRequest, opts ...grpc.CallOption) (*ListHostnamesResponse, error)
	DeleteHostname(ctx context.Context, in *DeleteHostnameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type waypointHznClient struct {
	cc grpc.ClientConnInterface
}

func NewWaypointHznClient(cc grpc.ClientConnInterface) WaypointHznClient {
	return &waypointHznClient{cc}
}

func (c *waypointHznClient) RegisterGuestAccount(ctx context.Context, in *RegisterGuestAccountRequest, opts ...grpc.CallOption) (*RegisterGuestAccountResponse, error) {
	out := new(RegisterGuestAccountResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.waypoint_hzn.WaypointHzn/RegisterGuestAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waypointHznClient) RegisterHostname(ctx context.Context, in *RegisterHostnameRequest, opts ...grpc.CallOption) (*RegisterHostnameResponse, error) {
	out := new(RegisterHostnameResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.waypoint_hzn.WaypointHzn/RegisterHostname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waypointHznClient) ListHostnames(ctx context.Context, in *ListHostnamesRequest, opts ...grpc.CallOption) (*ListHostnamesResponse, error) {
	out := new(ListHostnamesResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.waypoint_hzn.WaypointHzn/ListHostnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waypointHznClient) DeleteHostname(ctx context.Context, in *DeleteHostnameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/hashicorp.waypoint_hzn.WaypointHzn/DeleteHostname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaypointHznServer is the server API for WaypointHzn service.
type WaypointHznServer interface {
	RegisterGuestAccount(context.Context, *RegisterGuestAccountRequest) (*RegisterGuestAccountResponse, error)
	RegisterHostname(context.Context, *RegisterHostnameRequest) (*RegisterHostnameResponse, error)
	ListHostnames(context.Context, *ListHostnamesRequest) (*ListHostnamesResponse, error)
	DeleteHostname(context.Context, *DeleteHostnameRequest) (*empty.Empty, error)
}

// UnimplementedWaypointHznServer can be embedded to have forward compatible implementations.
type UnimplementedWaypointHznServer struct {
}

func (*UnimplementedWaypointHznServer) RegisterGuestAccount(ctx context.Context, req *RegisterGuestAccountRequest) (*RegisterGuestAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGuestAccount not implemented")
}
func (*UnimplementedWaypointHznServer) RegisterHostname(ctx context.Context, req *RegisterHostnameRequest) (*RegisterHostnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterHostname not implemented")
}
func (*UnimplementedWaypointHznServer) ListHostnames(ctx context.Context, req *ListHostnamesRequest) (*ListHostnamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHostnames not implemented")
}
func (*UnimplementedWaypointHznServer) DeleteHostname(ctx context.Context, req *DeleteHostnameRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHostname not implemented")
}

func RegisterWaypointHznServer(s *grpc.Server, srv WaypointHznServer) {
	s.RegisterService(&_WaypointHzn_serviceDesc, srv)
}

func _WaypointHzn_RegisterGuestAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGuestAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaypointHznServer).RegisterGuestAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.waypoint_hzn.WaypointHzn/RegisterGuestAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaypointHznServer).RegisterGuestAccount(ctx, req.(*RegisterGuestAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaypointHzn_RegisterHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaypointHznServer).RegisterHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.waypoint_hzn.WaypointHzn/RegisterHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaypointHznServer).RegisterHostname(ctx, req.(*RegisterHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaypointHzn_ListHostnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostnamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaypointHznServer).ListHostnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.waypoint_hzn.WaypointHzn/ListHostnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaypointHznServer).ListHostnames(ctx, req.(*ListHostnamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaypointHzn_DeleteHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaypointHznServer).DeleteHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.waypoint_hzn.WaypointHzn/DeleteHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaypointHznServer).DeleteHostname(ctx, req.(*DeleteHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WaypointHzn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.waypoint_hzn.WaypointHzn",
	HandlerType: (*WaypointHznServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterGuestAccount",
			Handler:    _WaypointHzn_RegisterGuestAccount_Handler,
		},
		{
			MethodName: "RegisterHostname",
			Handler:    _WaypointHzn_RegisterHostname_Handler,
		},
		{
			MethodName: "ListHostnames",
			Handler:    _WaypointHzn_ListHostnames_Handler,
		},
		{
			MethodName: "DeleteHostname",
			Handler:    _WaypointHzn_DeleteHostname_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
