name: hashicorp/waypoint-hzn/integration
on:
  push:
    branches:
    - main
env:
  GH_DOCKER_USER: xxxxxxx
jobs:
  dev-build:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/circleci/golang:1.14.3
    env:
      TEST_RESULTS_DIR: "/tmp/test-results"
      GOTESTSUM_RELEASE: 0.4.2
      EMAIL: noreply@hashicorp.com
      GIT_AUTHOR_NAME: circleci-waypoint
      GIT_COMMITTER_NAME: circleci-waypoint
      BASH_ENV: ".circleci/bash_env.sh"
      DOCKER_BUILDKIT: 1
    steps:
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - uses: actions/checkout@v3.5.0
    - uses: actions/download-artifact@v3.0.1
      with:
        path: "."
    - run: go build -o /go/bin/waypoint-hzn ./cmd/waypoint-hzn
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: "/go/bin/waypoint-hzn"
  image-release:
    if: github.ref == 'refs/heads/main'
    defaults:
#       # This item was not transformed because there is no suitable equivalent in GitHub Actions
#       run:
#         shell: "/usr/bin/env bash -euo pipefail -c"
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/base:2020.07-20.04
    needs:
    - dev-build
    env:
      TEST_RESULTS_DIR: "/tmp/test-results"
      GOTESTSUM_RELEASE: 0.4.2
      EMAIL: noreply@hashicorp.com
      GIT_AUTHOR_NAME: circleci-waypoint
      GIT_COMMITTER_NAME: circleci-waypoint
      BASH_ENV: ".circleci/bash_env.sh"
      DOCKER_BUILDKIT: 1
    steps:
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - uses: actions/checkout@v3.5.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - uses: actions/download-artifact@v3.0.1
      with:
        path: "."
    - name: 'Docker: Login to GitHub Package Registry'
      run: echo "$GH_DOCKER_PASS" | docker login docker.pkg.github.com --username $GH_DOCKER_USER --password-stdin
    - name: 'Docker: Build image'
      run: |-
        # Note that the "id_rsa_FOO" key name is based on the fingerprint of the SSH key
        # added in add_ssh_keys, but with colons removed.
        docker build \
          --ssh default \
          --secret id=ssh.config,src="${HOME}/project/.circleci/ssh_config" \
          --secret id=ssh.key,src="${HOME}/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98" \
          --progress=plain \
          -t docker.pkg.github.com/hashicorp/waypoint-hzn/waypoint-hzn-alpha:latest \
          .
    - name: 'Docker: Push image'
      run: docker push docker.pkg.github.com/hashicorp/waypoint-hzn/waypoint-hzn-alpha:latest
